# Configuration file for running the mnist_fc benchmark (large models).
general:
  # root_path: ../../vnncomp2022_benchmarks/benchmarks/mnist_yang
  # csv_name: instances.csv
  complete_verifier: skip
model:
  input_shape: [-1, 2]  # This onnx model has input shape [-1, 784] which is not compatible with our MIP solution
solver:
  # optimize_disjuncts_separately: true
  batch_size: 4096
  alpha-crown:
    apply_output_constraints_to: ["/input.19", "/input.23"]
  beta-crown:
    iteration: 20
    lr_beta: 0.03
    enable_opt_interm_bounds: True
  start_save_best: -1
bab:
  branching:
    candidates: 5
    reduceop: max
attack:
  pgd_order: skip